command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port=8080"

env:
  - name: LAKEBASE_POSTGRES_PROJECT
    value: support-ticket-app
  - name: LAKEBASE_POSTGRES_BRANCH
    value: production
  - name: LAKEBASE_POSTGRES_DATABASE
    value: databricks_postgres

resources:
  - name: lakebase
    lakebase:
      postgres:
        branch: ${LAKEBASE_POSTGRES_BRANCH}
        database: ${LAKEBASE_POSTGRES_DATABASE}