command:
  - "streamlit"
  - "run"
  - "app.py"

env:
  - name: DATABASE_URL
    value: postgresql://student:npg_kSuZ38gAynoV@ep-bitter-meadow-d81ncl50.database.us-east-2.cloud.databricks.com/databricks_postgres?sslmode=require