command:
  - "streamlit"
  - "run"
  - "app.py"

resources:
  - name: lakebase
    lakebase:
      postgres:
        branch: projects/support-ticket-app/branches/production
        database: projects/support-ticket-app/branches/production/databases/databricks-postgres